# Gradle
# Build your Java project and run tests with Apache Gradle.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

steps:
  - script: echo "My Azure Pipeline for Gradle project"
    displayName: 'Run a one-line script'

  - script: gradle build
    displayName: 'Build with Gradle'

  - script: gradle run
    displayName: 'Run the JAR file'

